config/routes.rb
Rails.application.routes.draw do
  resources :pucs
  resources :banks
  resources :movements

  root to: redirect('home')
  devise_for :users, controllers: {
    :registrations => "users/registrations"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'movements#home', as: 'home'
  get '/show', to: 'movements#show', as: 'show'
  get '/cupon', to: 'movements#_cupones_header', as: '_cupones_header'
  get '/webmaster', to: 'application#_superadmin_header', as: '_superadmin_header'

  get '/todos', to: 'movements#see_all', as: 'see_all'
  get '/weeks', to: 'movements#see_weeks', as: 'see_weeks'
  get '/months', to: 'movements#see_months', as: 'see_months'
  get '/tiempo', to: 'movements#see_tiempo', as: 'see_tiempo'

  get '/redes', to: 'movements#redes', as: 'redes'
  get '/chat', to: 'movements#rs_chat', as: 'rs_chat'
  get '/agenda', to: 'movements#rs_agenda', as: 'rs_agenda'
  get '/eventos', to: 'movements#rs_eventos', as: 'rs_eventos'
  get '/notas', to: 'movements#rs_notas', as: 'rs_notas'

  get '/datos', to: 'movements#data', as: 'data'
  get '/bancos', to: 'banks#index', as: 'bancos'
  get '/bancol', to: 'banks#b_bancol', as: 'b_bancol'
  get '/bogota', to: 'banks#b_bogota', as: 'b_bogota'
  get '/daviv',  to: 'banks#b_daviv', as: 'b_daviv'

  get '/contab', to: 'movements#contab', as: 'contab'
  get '/finanzas', to: 'movements#finanzas', as: 'finanzas'
  get '/credit', to: 'movements#credit', as: 'credit'

  get '/movmed', to: 'movements#movmed', as: 'movmed'
  get '/leyes', to: 'movements#n_leyes', as: 'n_leyes'
  get '/normas', to: 'movements#normas', as: 'normas'
  get '/pp', to: 'movements#movm_pp', as: 'movm_pp'
  get '/runt', to: 'movements#n_runt', as: 'n_runt'

  get '/flota', to: 'movements#tr_flota', as: 'tr_flota'
  get '/andaluz', to: 'movements#vx_andaluz', as: 'vx_andaluz'
  get '/athos', to: 'movements#vx_athos', as: 'vx_athos'
  get '/athos_bitac', to: 'movements#vx_athos_bitac', as: 'vx_athos_bitac'
  get '/athos_matric', to: 'movements#vx_athos_matric', as: 'vx_athos_matric'
  get '/taxis', to: 'movements#vx_taxis', as: 'vx_taxis'

  get '/coltrans', to: 'movements#tr_coltrans', as: 'tr_coltrans'
  get '/dimax', to: 'movements#vc_dimax_', as: 'vc_dimax_'
  get '/dimax_agree', to: 'movements#vc_dmx_contratos', as: 'vc_dmx_contratos'
  get '/dimax_bitac', to: 'movements#vc_dimax_bitac', as: 'vc_dimax_bitac'
  get '/dimax_matric', to: 'movements#vc_dimax_matric', as: 'vc_dimax_matric'

  get '/autos', to: 'movements#vc_autos', as: 'vc_autos'
  get '/golf', to: 'movements#vc_golf_', as: 'vc_golf_'
  get '/piaggio', to: 'movements#vm_piaggio', as: 'vm_piaggio'

  get '/taller', to: 'movements#tr_taller', as: 'tr_taller'
  get '/mec_aut', to: 'movements#tr_tutors', as: 'tr_tutors'

  as :user do
    get 'admin', to: 'devise/sessions#new'
    get 'reset_password', to: 'devise/passwords#new'
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  end
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :users
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :authenticate_user!, only: [:home_admin]
  before_action :set_movement, only: [:show, :edit, :update, :destroy]

  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.where(mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day))

    # Estado general actual
    @act_in = Movement.where(mov_type: 'I', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_eg = Movement.where(mov_type: 'E', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_ev = @act_eg.nonzero? ? @act_in/@act_eg : 0
    @act_pj = Movement.where(mov_type: 'J', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)

    @act_an = Movement.where(mov_type: 'Aª', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_dt = Movement.where(mov_type: 'A°', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)

    @act_so = Movement.where(mov_type: 'S°', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_to = Movement.where(mov_type: 'T°', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_tx = Movement.where(mov_type: 'T×', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_tm = Movement.where(mov_type: 'T™', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_tn = @act_so + @act_to + @act_tx + @act_tm

    @act_tr = Movement.where(mov_type: 'T', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_vr = Movement.where(mov_type: 'V', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_oo = @act_pj + @act_an+@act_dt + @act_so+@act_to+@act_tx+@act_tm + @act_tr+@act_vr
    @act_na = @act_in - (@act_eg + @act_oo)

    # Financiera - Cuotas, inter_mora, seguro_crédito
    @act_fn = Movement.where(mov_type: 'Fª', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_fi = Movement.where(mov_type: 'F°', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_sg = Movement.where(mov_type: 'F×', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_nf = @act_na - (@act_fn + @act_fi + @act_sg)

    # Contabilidad personal general
    @act_cd = Movement.where(mov_type: 'D', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_cc = Movement.where(mov_type: 'C', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)

    @act_im = Movement.where(mov_type: 'M', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_lg = Movement.where(mov_type: 'L', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_ot = Movement.where(mov_type: 'O', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)

    @act_hm = Movement.where(mov_type: 'H', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_ps = Movement.where(mov_type: 'P', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_ss = Movement.where(mov_type: 'S', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_day )).sum(:price)
    @act_vs = @act_im + @act_lg + @act_ot + @act_hm + @act_ps + @act_ss
    @act_nc = (@act_nf + @act_cd) - (@act_cc + @act_vs)

    # Finanzas2 - Créditos(Préstamos2), pagos, intereses
    @act_fp = Movement.where(mov_type: 'F¹', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_fg = Movement.where(mov_type: 'F²', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_fr = Movement.where(mov_type: 'F³', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_fz = (@act_nc + @act_fp) - (@act_fg + @act_fr)

    # Bancos - Estado Operaciones en [Contab]
    @act_bd = Movement.where(mov_type: 'Bd', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_bc = Movement.where(mov_type: 'Bc', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_bk = Movement.where(mov_type: 'ß',  mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_day )).sum(:price)
    @act_tb = (@act_fz + @act_bc) - (@act_bd + @act_bk)
    # Nota: se invierten bd(consig_bank=ret_caja) y bc(ret_bank=reinteg_caja)


    # ----------------------------------------------
    # Estado Actual - // Día / Sem / Mes / Año //
    # ----------------------------------------------
    @ad_in = Movement.where(mov_type: 'I', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_in = Movement.where(mov_type: 'I', mov_date: (Time.zone.now.beginning_of_week-1.day..Time.zone.now.end_of_week-1.day)).sum(:price)
    @am_in = Movement.where(mov_type: 'I', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_in = Movement.where(mov_type: 'I', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_month)).sum(:price)
    @am_iv = @am_in/30
    @a17a_in=Movement.where(mov_type: 'I', mov_date: (Date.new(2017,014,11)..Date.new(2017,014,31) )).sum(:price)
    @a18a_in=Movement.where(mov_type: 'I', mov_date: (Date.new(2018, 1, 1)..Date.new(2018, 6,30))).sum(:price)
    @a18b_in=Movement.where(mov_type: 'I', mov_date: (Date.new(2018, 7, 1)..Date.new(2018,12,31))).sum(:price)
    @a19a_in=Movement.where(mov_type: 'I', mov_date: (Date.new(2019, 1, 1)..Date.new(2019, 6,30))).sum(:price)
    @a19b_in=Movement.where(mov_type: 'I', mov_date: (Date.new(2019, 7, 1)..Date.new(2019,12,31))).sum(:price)

    @ad_eg = Movement.where(mov_type: 'E', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_eg = Movement.where(mov_type: 'E', mov_date: (Time.zone.now.beginning_of_week-1..Time.zone.now.end_of_week-1)).sum(:price)
    @am_eg = Movement.where(mov_type: 'E', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_eg = Movement.where(mov_type: 'E', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_month)).sum(:price)
    @am_ev = @am_eg.nonzero? ? @am_in/@am_eg : 0
    @a17a_eg=Movement.where(mov_type: 'E', mov_date: (Date.new(2017,014,11)..Date.new(2017,014,31) )).sum(:price)
    @a18a_eg=Movement.where(mov_type: 'E', mov_date: (Date.new(2018, 1, 1)..Date.new(2018, 6,30))).sum(:price)
    @a18b_eg=Movement.where(mov_type: 'E', mov_date: (Date.new(2018, 7, 1)..Date.new(2018,12,31))).sum(:price)
    @a19a_eg=Movement.where(mov_type: 'E', mov_date: (Date.new(2019, 1, 1)..Date.new(2019, 6,30))).sum(:price)
    @a19b_eg=Movement.where(mov_type: 'E', mov_date: (Date.new(2019, 7, 1)..Date.new(2019,12,31))).sum(:price)

    @ad_pj = Movement.where(mov_type: 'J', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_pj = Movement.where(mov_type: 'J', mov_date: (Time.zone.now.beginning_of_week-1..Time.zone.now.end_of_week-1)).sum(:price)
    @am_pj = Movement.where(mov_type: 'J', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_pj = Movement.where(mov_type: 'J', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_month)).sum(:price)
    @a17a_pj=Movement.where(mov_type: 'J', mov_date: (Date.new(2017,014,11)..Date.new(2017,014,31) )).sum(:price)
    @a18a_pj=Movement.where(mov_type: 'J', mov_date: (Date.new(2018, 1, 1)..Date.new(2018, 6,30))).sum(:price)
    @a18b_pj=Movement.where(mov_type: 'J', mov_date: (Date.new(2018, 7, 1)..Date.new(2018,12,31))).sum(:price)
    @a19a_pj=Movement.where(mov_type: 'J', mov_date: (Date.new(2019, 1, 1)..Date.new(2019, 6,30))).sum(:price)
    @a19b_pj=Movement.where(mov_type: 'J', mov_date: (Date.new(2019, 7, 1)..Date.new(2019,12,31))).sum(:price)

    # Andaluz / Datos / Seguridad Social
    @ad_an = Movement.where(mov_type: 'Aª', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_an = Movement.where(mov_type: 'Aª', mov_date: (Time.zone.now.beginning_of_week-1..Time.zone.now.end_of_week-1)).sum(:price)
    @am_an = Movement.where(mov_type: 'Aª', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @a17a_an=Movement.where(mov_type: 'Aª', mov_date: (Date.new(2017,014,11)..Date.new(2017,014,31) )).sum(:price)
    @a18a_an=Movement.where(mov_type: 'Aª', mov_date: (Date.new(2018, 1, 1)..Date.new(2018, 6,30))).sum(:price)
    @a18b_an=Movement.where(mov_type: 'Aª', mov_date: (Date.new(2018, 7, 1)..Date.new(2018,12,31))).sum(:price)
    @a19a_an=Movement.where(mov_type: 'Aª', mov_date: (Date.new(2019, 1, 1)..Date.new(2019, 6,30))).sum(:price)
    @a19b_an=Movement.where(mov_type: 'Aª', mov_date: (Date.new(2019, 7, 1)..Date.new(2019,12,31))).sum(:price)
    @ay_an = Movement.where(mov_type: 'Aª', mov_date: (Date.new(2017,014,11)..Time.zone.now.end_of_month)).sum(:price)
    @ay_av = @ay_an.nonzero? ? (@ay_in/@ay_an)/1000 : 0

    @ad_dt = Movement.where(mov_type: 'A°', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_dt = Movement.where(mov_type: 'A°', mov_date: (Time.zone.now.beginning_of_week-1..Time.zone.now.end_of_week-1)).sum(:price)
    @am_dt = Movement.where(mov_type: 'A°', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @a17a_dt=Movement.where(mov_type: 'A°', mov_date: (Date.new(2017,014,11)..Date.new(2017,014,31) )).sum(:price)
    @a18a_dt=Movement.where(mov_type: 'A°', mov_date: (Date.new(2018, 1, 1)..Date.new(2018, 6,30))).sum(:price)
    @a18b_dt=Movement.where(mov_type: 'A°', mov_date: (Date.new(2018, 7, 1)..Date.new(2018,12,31))).sum(:price)
    @a19a_dt=Movement.where(mov_type: 'A°', mov_date: (Date.new(2019, 1, 1)..Date.new(2019, 6,30))).sum(:price)

app/helpers/movements_helper.rb
module MovementsHelper
  def to_currency(number)
    number_to_currency(number, unit: "", precision: 0, format: "%u%n")
  end

  def to_hour(hour)
    eval(hour)[4].to_s + ':' + eval(hour)[5].to_s
  end

  def mov_types
    [['Ingreso', 'I'],
     ['Egreso', 'E'],
     ['Peajes', 'J'],

     ['Andaluz', 'Aª'],
     ['Datos_Móvil', 'A°'],
     ['Taller', 'T'],
     ['Varios', 'V'],
     ['---------------', ''],

     ['Home', 'H'],
     ['Personal', 'P'],
     ['Seg_Soc', 'S'],

     ['_________ Contab', ''],
     ['Débitos', 'D'],
     ['Créditos', 'C'],

     ['Préstamos', 'F¹'],
     ['Pagos', 'F²'],
     ['Prests_%', 'F³'],

     ['Impuestos', 'M'],
     ['Legal', 'L'],
     ['Otros', 'O'],

     ['________ Gts Fijos', ''],
     ['SOAT', 'S°'],
     ['Tarjeta_Operac', 'T°'],
     ['Taximetro', 'T×'],
     ['Téc_Méc', 'T™'],

     ['________ Financ', ''],
     ['Financiera', 'Fª'],
     ['Financ_%', 'F°'],
     ['Servicrédito', 'F×'],

     ['_________ Apart', ''],
     ['Bog1_Apartadó_Cons', 'Bª'],
     ['Bog1_Apartadó_Rets', 'Bº'],
     ['Bog1_Apartadó_Costos', 'Bæ'],

     ['_________ Med_Est', ''],
     ['Bog2_Estadio_Cons', 'Bd'],
     ['Bog2_Estadio_Rets', 'Bc'],
     ['Bog2_Estadio_Costos', 'ß'],

     ['_________ Bancos', ''],
     ['Bank_Dep', 'B¹'],
     ['Bank_Ret', 'B²'],
     ['Bank_CsF', 'B³'],
     ['Banks_vr', 'B°'],

     ['_________ STU379', ''],
     ['Ingreso9', 'I×'],
     ['Egreso9', 'E×'],
     ['Gst_Operac', 'O×'],
     ['Móvil Éxit9', 'A×'],
     ['Liquid9', 'L×'],
     ['Varios9', 'V×'],
     ['Taller9', 'U×'],

    ]

  end
end

app/views/movements/data.html.erb
<nav class="header-reg">
  <%= link_to 'Nuevo', new_movement_path %>
  <%= link_to 'Día', movements_path %> <!-- Día, nuevo, consolidados -->

  <%= link_to 'Bancos', banks_path %>  <!-- Bancos, Corp_Ahorros .. -->
  <%= link_to 'Contab', contab_path %>  <!-- Contabilidad, Caja, .. -->
  <%= link_to 'Finanzas', finanzas_path %>  <!-- Agenda -->
  <%= link_to 'Seguros', '#' %>   <!-- ... -->
</nav>

<div>  <center>
  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Datos </span> <%= link_to 'Back', movements_path %>
    <span> Coltax OnLine </span>  </h3>
  <h4> Datos </h4> </center>

  <P>Bancos
  <br>Contabilidad
  <br>Finanzas<br>

  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Footer </span> <%= link_to 'Back', data_path %> <span> Datos / Coltax </span> </h3>

  <table width=100%>
    <tr><td class="olive2">
            <nav class="header-reg">
              <ul><li> Créditos </li>
                  <li> Inversiones </li>
                  <li> Libre Inversión </li>
              </ul>
            </nav>
        </td>

        <!-- <td>''</td> -->
        <td class="olive3">
            <nav class="header-reg">
              <ul><li> Leasing </li>
                  <li> Vivienda </li>
                  <li> Otros  </li>
              </ul>
            </nav>
        </td>
    </tr>

    <tr><td class="darkgreen" colspan=6>
            <nav class="header-reg marin3">
              <ul><li> Cooperativa de Ahorros de Antioquia </li>
              </ul>
            </nav>
        </td>
    </tr>
  </table>

</div>

<h6 class="green">Footer</h6>
<span><%= link_to 'Return Finances', finanzas_path %></span>

app/views/movements/edit.html.erb
<div class="container-coltax">
  <h4 style="text-align: right">Editar movimiento ◄ </h4>
  <%= render 'form', movement: @movement %>
</div>

app/views/movements/movmed.html.erb
<nav class="header-reg">
  <%= link_to 'Nuevo', new_movement_path %>
  <%= link_to 'Día', movements_path %>  <!-- Díario, consolidados -->

  <%= link_to 'Normas', normas_path %> <!-- Normatividad Legal -->
  <%= link_to 'Sites', '#' %>   <!-- ... -->

  <%= link_to 'Runt', n_runt_path %>  <!-- Pagos x infracciones  -->
  <%= link_to 'Simit', '#' %>    <!-- Simit -->
  <%= link_to 'P&P', movm_pp_path %>  <!-- Pico y Placa Med -->
</nav>

<div> <center>
  <h6 style="display: flex; justify-content: space-between; width: 100%;">
    <span> ♦ Index </span> <%= link_to '◄', movements_path %>
    <%= link_to '►', normas_path %> <span> Normas • </span> </h6>
  <H4> Movilidad Medellín </h4> </center>

  <P>
  <nav>
    <ul><li> ABC... </li>

        <li> Trámites </li>
        <li> Pico y Placa </li>

        <li> Fotomultas </li>

        <li> Taquilla </li>


        <li> Otros </li>
    </ul>
  </nav>

</div>

app/views/movements/redes.html.erb
<nav class="header-reg">
  <%= link_to 'Nuevo!', new_movement_path %>
  <%= link_to 'Día', movements_path %> <!-- Día, nuevo, consolidados -->

  <%= link_to 'Chat', rs_chat_path %>  <!-- Enlaces online -->
  <%= link_to 'Agenda', rs_agenda_path %>  <!-- Agenda -->
  <%= link_to 'Eventos', rs_eventos_path %> <!-- Eventos, Estadio, Macarena, TT, JPII... -->
  <%= link_to 'Notas', rs_notas_path %>    <!-- Notas -->
  <%= link_to '?', '#' %>  <!-- Pagos x infracciones  -->

</nav>

<h3 style="display: flex; justify-content: space-between; width: 100%;">
  <span>Redes</span> <%= link_to 'Back', movements_path %> <span>Coltax OnLine</span> </h3>

<hr class="separator">

<iframe width="458" height="257" src="https://www.youtube.com/embed/PbEEae8mMLw" frameborder="0"
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen> Máximas de San Pablo de la Cruz IV </iframe>

<!-- <iframe width="458" height="257" src="https://www.youtube.com/embed/LugSZy4xg38?list=RDLugSZy4xg38"
frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
allowfullscreen></iframe> -->

<hr class="separator">

<div> <center>
  <H4> Redes Sociales </h4> </center>

  <P>
  <nav>
    <ul><P>
        <li> <a href="http://caracol.com.co/emisora/medellin/"> <B>Caracol - Medellín</B> </a> </li>
        <li> <a href="https://radios.com.co/besame-medellin"> <B> La Voz de Colombia - Bésame </B> </a> </li>
        <li> <a href="https://envivo.besame.fm/"> <B> La Voz de Colombia - Bésame en vivo </B> </a> </li>

        <hr width=70%>
        <li> <a href="www"> <B> Blue Radio </B> </a> </li>
        <li> <a href="www"> <B> La W </B> </a> </li>

        <hr width=70%>
        <li> <a href="http://www.espn.com/fantasy/"> <B><I> ESPN </I></B> </a> </li>
        <li> <a href="http://www.+espn.com/fantasy/"><B><I> ESPN+ </I></B> </a> </li>

        <hr width=70%>
        <li> <a href="https://www.youtube.com/watch?v=FEkwlBVuxqM">
             <B> Las 100 Mejores Rancheras </B> </a> </li>

        <hr width=70%>
        <li> <a href="https://www.youtube.com/watch?v=sab0aARbjtY">
             <B> Si no TE CONFIESAS de tus PECADOS, SATANÁS te acusará en tu JUICIO </B> </a> </li>

    </ul>
  </nav>

  <hr width=70%>


  <!-- <hr class="separator"> -->
  <div style="background-color: white; ">
    <a href="https://twitter.com/i/status/1086216669670920193"> ► Rescate de peces en Río Cauca</a><br>
    <a href="https://twitter.com/i/status/1086216669670920193"> ► Rescate de peces en Río Cauca</a>
  </div>

  <div class="celeste">
    <h5 class="yellow"><a href="https://twitter.com/i/status/1086216669670920193"> ► Rescate de peces en Río Cauca</a></h5>
    <h6 class="red"><a href="https://twitter.com/i/status/1086216669670920193"> ► Rescate de peces en Río Cauca</a></h6>
  </div>


</div>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @movement.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @movement.mov_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movement.description %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>

app/views/movements/vc_autos.html.erb
<nav class="header-reg">
  <%= link_to 'Nuevo', new_movement_path %>
  <%= link_to 'Día', movements_path %> <!-- Día, nuevo, consolidados -->

  <%= link_to 'Athos', vx_athos_path %>  <!-- Estados, Informs, imprs -->
  <%= link_to 'Dimax', vc_dimax__path %>   <!-- ... -->
  <%= link_to 'Golf', vc_golf__path %>   <!-- ... -->
  <%= link_to 'Piaggio', vm_piaggio_path %>   <!-- ENX31A -->
</nav>


<div style = "color: white"; > <center>
  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Flota </span> ◄ <%= link_to '◄',tr_flota_path %>
    <%= link_to '►', data_path %> ► <span>Coltax OnLine</span> </h3>
  <h4> Coltrans - Operación Nacional </h4>
</center>

  <P>
  <nav>
    <ul><li> Autos </li>
        <li> Videos </li>
        <li> ----------------- </li>
        <li> Autocab </li>
        <li> Cursos </li>
        <li> ----------------- </li>
        <li> Especiales </li>
    </ul>
  </nav>

  <P><center><h3> Volkswagwn Golf - MAP654 </h3> </center>

  <table width=100%> <P>
    <tr><td class="olive2">
            <nav class="header-reg">
              <ul><li> Almacenes </li>
                  <li> Manuales </li>
                  <li> Repuestos </li>
              </ul>
            </nav>
        </td>

        <td> </td>

        <td class="olive3">
            <nav class="header-reg">
              <ul><li> Serviteca </li>
                  <li> Mecánicos </li>
                  <li> Tutoriales </li>
              </ul>
            </nav>
        </td>
    </tr>

    <tr><td class="darkgreen" colspan=6> <center>
            <nav class="header-reg marin3">
              <ul><li> Club Motoristas de Antioquia </li> </ul>
            </nav> </center>
        </td>
    </tr>
  </table>

</div>