config/routes.rb
Rails.application.routes.draw do
  resources :pucs
  resources :banks
  resources :movements

  root to: redirect('home')
  devise_for :users, controllers: {
    :registrations => "users/registrations"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'movements#home', as: 'home'
  get '/show', to: 'movements#show', as: 'show'
  get '/cupon', to: 'movements#_cupones_header', as: '_cupones_header'
  get '/webmaster', to: 'application#_superadmin_header', as: '_superadmin_header'

  get '/todos', to: 'movements#see_all', as: 'see_all'
  get '/weeks', to: 'movements#see_weeks', as: 'see_weeks'
  get '/months', to: 'movements#see_months', as: 'see_months'
  get '/tiempo', to: 'movements#see_tiempo', as: 'see_tiempo'

  get '/redes', to: 'movements#redes', as: 'redes'
  get '/chat', to: 'movements#rs_chat', as: 'rs_chat'
  get '/agenda', to: 'movements#rs_agenda', as: 'rs_agenda'
  get '/eventos', to: 'movements#rs_eventos', as: 'rs_eventos'
  get '/notas', to: 'movements#rs_notas', as: 'rs_notas'

  get '/datos', to: 'movements#data', as: 'data'
  get '/bancos', to: 'banks#index', as: 'bancos'
  get '/bancol', to: 'banks#b_bancol', as: 'b_bancol'
  get '/bogota', to: 'banks#b_bogota', as: 'b_bogota'
  get '/daviv',  to: 'banks#b_daviv', as: 'b_daviv'

  get '/contab', to: 'movements#contab', as: 'contab'
  get '/finanzas', to: 'movements#finanzas', as: 'finanzas'
  get '/credit', to: 'movements#credit', as: 'credit'

  get '/movmed', to: 'movements#movmed', as: 'movmed'
  get '/leyes', to: 'movements#n_leyes', as: 'n_leyes'
  get '/normas', to: 'movements#normas', as: 'normas'
  get '/pp', to: 'movements#movm_pp', as: 'movm_pp'
  get '/runt', to: 'movements#n_runt', as: 'n_runt'

  get '/flota', to: 'movements#tr_flota', as: 'tr_flota'
  get '/andaluz', to: 'movements#vx_andaluz', as: 'vx_andaluz'
  get '/athos', to: 'movements#vx_athos', as: 'vx_athos'
  get '/athos_bitac', to: 'movements#vx_athos_bitac', as: 'vx_athos_bitac'
  get '/athos_matric', to: 'movements#vx_athos_matric', as: 'vx_athos_matric'
  get '/taxis', to: 'movements#vx_taxis', as: 'vx_taxis'

  get '/coltrans', to: 'movements#tr_coltrans', as: 'tr_coltrans'
  get '/dimax', to: 'movements#vc_dimax_', as: 'vc_dimax_'
  get '/dimax_agree', to: 'movements#vc_dmx_contratos', as: 'vc_dmx_contratos'
  get '/dimax_bitac', to: 'movements#vc_dimax_bitac', as: 'vc_dimax_bitac'
  get '/dimax_matric', to: 'movements#vc_dimax_matric', as: 'vc_dimax_matric'

  get '/autos', to: 'movements#vc_autos', as: 'vc_autos'
  get '/golf', to: 'movements#vc_golf_', as: 'vc_golf_'
  get '/piaggio', to: 'movements#vm_piaggio', as: 'vm_piaggio'

  get '/taller', to: 'movements#tr_taller', as: 'tr_taller'
  get '/mec_aut', to: 'movements#tr_tutors', as: 'tr_tutors'

  as :user do
    get 'admin', to: 'devise/sessions#new'
    get 'reset_password', to: 'devise/passwords#new'
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  end
end

app/models/puc.rb
class Puc < ApplicationRecord
end

app/controllers/pucs_controller.rb
class PucsController < ApplicationController
  before_action :set_puc, only: [:show, :edit, :update, :destroy]

  # GET /pucs
  # GET /pucs.json
  def index
    @pucs = Puc.all
  end

  # GET /pucs/1
  # GET /pucs/1.json
  def show
  end

  # GET /pucs/new
  def new
    @puc = Puc.new
  end

  # GET /pucs/1/edit
  def edit
  end

  # POST /pucs
  # POST /pucs.json
  def create
    @puc = Puc.new(puc_params)

    respond_to do |format|
      if @puc.save
        format.html { redirect_to @puc, notice: 'Puc was successfully created.' }
        format.json { render :show, status: :created, location: @puc }
      else
        format.html { render :new }
        format.json { render json: @puc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pucs/1
  # PATCH/PUT /pucs/1.json
  def update
    respond_to do |format|
      if @puc.update(puc_params)
        format.html { redirect_to @puc, notice: 'Puc was successfully updated.' }
        format.json { render :show, status: :ok, location: @puc }
      else
        format.html { render :edit }
        format.json { render json: @puc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pucs/1
  # DELETE /pucs/1.json
  def destroy
    @puc.destroy
    respond_to do |format|
      format.html { redirect_to pucs_url, notice: 'Puc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puc
      @puc = Puc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puc_params
      params.require(:puc).permit(:code, :name, :puc_type, :detail, :puc_class, :category)
    end
end

app/helpers/pucs_helper.rb
module PucsHelper

  
end

app/views/pucs/_form.html.erb
<%= form_for(puc) do |f| %>
  <% if puc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puc.errors.count, "error") %> prohibited this puc from being saved:</h2>

      <ul>
      <% puc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :puc_type %>
    <%= f.text_field :puc_type %>
  </div>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>

  <div class="field">
    <%= f.label :puc_class %>
    <%= f.text_field :puc_class %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pucs/edit.html.erb
<h1>Editing Puc</h1>

<%= render 'form', puc: @puc %>

<%= link_to 'Show', @puc %> |
<%= link_to 'Back', pucs_path %>

app/views/pucs/index.html.erb
<div class="container-coltax">
  <div class="header-reg">
    <%= link_to 'New!', new_puc_path %>
    <%= link_to 'Cuentas', '#' %>    <!-- Ver PUC completo -->
    <%= link_to 'Balance', '#' %>  <!-- Balance General / partida doble -->
    <%= link_to 'Resultados', '#' %>  <!-- Reultados: Ingresos y Egresos -->

    <%= link_to 'Red', redes_path %>   <!-- Redes sociales, alertas, mensajes -->
    <%= link_to '?', '#' %>   <!-- Ayuda -->
  </div>

  <div> <center>
    <h3 style="display: flex; justify-content: space-between; width: 100%;">
      <span> PUC </span> <%= link_to 'Back', contab_path %>
      <span> Coltax OnLine </span> </h3>
    <h4> Plan Único de Cuentas </h4> </center>
  </div>  <!-- <h4><I><U></U></I></h4> -->

  <table class="table table-hover table-striped datatable-plugin">
    <thead>  <!-- Registros -->
      <tr>
        <th>Class</th>
        <th>Cat</th>
        <th>Code</th>
        <th>Name</th>
        <th>T</th>
        <th>Detail</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
    <% @pucs.each_with_index do |puc, index| %>
      <tr>
        <td><%= puc.puc_class %></td>
        <td><%= puc.category %></td>
        <td><%= puc.code %></td>
        <td><%= puc.name %></td>
        <td><%= puc.puc_type %></td>
        <td><%= puc.detail %></td>

        <!-- <td><%= index + 1 %></td> -->
        <!-- <td><%= link_to 'Show', puc %></td> -->
        <td><%= link_to 'Edit', edit_puc_path(puc) %></td>
        <td><%= link_to 'Destroy', puc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Puc', new_puc_path %><P>


<!-- <br>   -->

<p id="notice"><%= notice %></p>

</div>

app/views/pucs/new.html.erb
<h1>New Puc</h1>

<%= render 'form', puc: @puc %>

<%= link_to 'Back', pucs_path %>

app/views/pucs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @puc.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @puc.name %>
</p>

<p>
  <strong>Puc type:</strong>
  <%= @puc.puc_type %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @puc.detail %>
</p>

<p>
  <strong>Puc class:</strong>
  <%= @puc.puc_class %>
</p>

<p>
  <strong>Category:</strong>
  <%= @puc.category %>
</p>

<%= link_to 'Edit', edit_puc_path(@puc) %> |
<%= link_to 'Back', pucs_path %>