config/routes.rb
Rails.application.routes.draw do
  resources :pucs
  resources :banks
  resources :movements

  root to: redirect('home')
  devise_for :users, controllers: {
    :registrations => "users/registrations"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'movements#home', as: 'home'
  get '/show', to: 'movements#show', as: 'show'
  get '/cupon', to: 'movements#_cupones_header', as: '_cupones_header'
  get '/webmaster', to: 'application#_superadmin_header', as: '_superadmin_header'

  get '/todos', to: 'movements#see_all', as: 'see_all'
  get '/weeks', to: 'movements#see_weeks', as: 'see_weeks'
  get '/months', to: 'movements#see_months', as: 'see_months'
  get '/tiempo', to: 'movements#see_tiempo', as: 'see_tiempo'

  get '/redes', to: 'movements#redes', as: 'redes'
  get '/chat', to: 'movements#rs_chat', as: 'rs_chat'
  get '/agenda', to: 'movements#rs_agenda', as: 'rs_agenda'
  get '/eventos', to: 'movements#rs_eventos', as: 'rs_eventos'
  get '/notas', to: 'movements#rs_notas', as: 'rs_notas'

  get '/datos', to: 'movements#data', as: 'data'
  get '/bancos', to: 'banks#index', as: 'bancos'
  get '/bancol', to: 'banks#b_bancol', as: 'b_bancol'
  get '/bogota', to: 'banks#b_bogota', as: 'b_bogota'
  get '/daviv',  to: 'banks#b_daviv', as: 'b_daviv'

  get '/contab', to: 'movements#contab', as: 'contab'
  get '/finanzas', to: 'movements#finanzas', as: 'finanzas'
  get '/credit', to: 'movements#credit', as: 'credit'

  get '/movmed', to: 'movements#movmed', as: 'movmed'
  get '/leyes', to: 'movements#n_leyes', as: 'n_leyes'
  get '/normas', to: 'movements#normas', as: 'normas'
  get '/pp', to: 'movements#movm_pp', as: 'movm_pp'
  get '/runt', to: 'movements#n_runt', as: 'n_runt'

  get '/flota', to: 'movements#tr_flota', as: 'tr_flota'
  get '/andaluz', to: 'movements#vx_andaluz', as: 'vx_andaluz'
  get '/athos', to: 'movements#vx_athos', as: 'vx_athos'
  get '/athos_bitac', to: 'movements#vx_athos_bitac', as: 'vx_athos_bitac'
  get '/athos_matric', to: 'movements#vx_athos_matric', as: 'vx_athos_matric'
  get '/taxis', to: 'movements#vx_taxis', as: 'vx_taxis'

  get '/coltrans', to: 'movements#tr_coltrans', as: 'tr_coltrans'
  get '/dimax', to: 'movements#vc_dimax_', as: 'vc_dimax_'
  get '/dimax_agree', to: 'movements#vc_dmx_contratos', as: 'vc_dmx_contratos'
  get '/dimax_bitac', to: 'movements#vc_dimax_bitac', as: 'vc_dimax_bitac'
  get '/dimax_matric', to: 'movements#vc_dimax_matric', as: 'vc_dimax_matric'

  get '/autos', to: 'movements#vc_autos', as: 'vc_autos'
  get '/golf', to: 'movements#vc_golf_', as: 'vc_golf_'
  get '/piaggio', to: 'movements#vm_piaggio', as: 'vm_piaggio'

  get '/taller', to: 'movements#tr_taller', as: 'tr_taller'
  get '/mec_aut', to: 'movements#tr_tutors', as: 'tr_tutors'

  as :user do
    get 'admin', to: 'devise/sessions#new'
    get 'reset_password', to: 'devise/passwords#new'
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
  belongs_to :users
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end


  # GET /banks/new
  def index
    @banks = Bank.all

    @movements = Movement.all

    # Bancos /All
    @ad_bd = Movement.where(mov_type: 'B¹', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_bd = Movement.where(mov_type: 'B¹', mov_date: (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week)).sum(:price)
    @am_bd = Movement.where(mov_type: 'B¹', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_bd = Movement.where(mov_type: 'B¹', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_year)).sum(:price)

    @ad_br = Movement.where(mov_type: 'B²', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_br = Movement.where(mov_type: 'B²', mov_date: (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week)).sum(:price)
    @am_br = Movement.where(mov_type: 'B²', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_br = Movement.where(mov_type: 'B²', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_year)).sum(:price)

    @ad_bc = Movement.where(mov_type: 'B³', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_bc = Movement.where(mov_type: 'B³', mov_date: (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week)).sum(:price)
    @am_bc = Movement.where(mov_type: 'B³', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_bc = Movement.where(mov_type: 'B³', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_year)).sum(:price)

    @ad_bo = Movement.where(mov_type: 'B°', mov_date: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).sum(:price)
    @aw_bo = Movement.where(mov_type: 'B°', mov_date: (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week)).sum(:price)
    @am_bo = Movement.where(mov_type: 'B°', mov_date: (Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)).sum(:price)
    @ay_bo = Movement.where(mov_type: 'B°', mov_date: (Date.new(2017,014, 1)..Time.zone.now.end_of_year)).sum(:price)

    @ad_nb = @ad_bd - (@ad_br + @ad_bc+ @ad_bo)
    @aw_nb = @aw_bd - (@aw_br + @aw_bc+ @aw_bo)
    @am_nb = @am_bd - (@am_br + @am_bc+ @am_bo)
    @ay_nb = @ay_bd - (@ay_br + @ay_bc+ @ay_bo)
    @nn_n  = 0


  end




  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new

    @user_name = current_user.nil? ? '' : User.where(id: current_user.id).email

    if @bank.puc.eql? "110101"
       @puc_name = "Caja"
    end
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:puc, :tran_type, :detail, :trans_value, :balance, :bank_id, :bank, :users_id, :verified)
    end
end

app/helpers/banks_helper.rb
module BanksHelper

  def trans_types
    [
      ['Débito', 'D'],
      ['Crédito', 'C'],
    ]
  end
end

app/views/banks/_form.html.erb
<!-- banks -->
<%= form_for(bank) do |f| %>
  <% if bank.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(bank.errors.count, "error") %>
           prohibited this bank from being saved:</h3>
      <ul>
      <% bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-4">
    <%= f.label :user_id, 'User' %>
    <%= f.text_field :user_id, value: @user_name, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-xs-3">
    <%= f.label :bank_id, 'CB' %>
    <%= f.text_field :bank_id, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-xs-5">
    <% @bank.bank = @bank.bank_id == "1" ? "BanBogotá" : "" %>
    <%= f.label :bank, 'Banco' %>
    <%= f.text_field :bank, class: 'form-control', required: true %>
  </div>


  <div class="form-group col-xs-4">
    <%= f.label :puc, 'Cuenta' %>
    <%= f.text_field :puc, type: "number", class: 'form-control', required: true %>
    <%= @puc_name %>
  </div>

  <div class="form-group col-xs-3">
    <%= f.label :trans_type, 'Tipo' %>
    <%= f.select_tag :trans_type, options_for_select(trans_types, @bank.trans_type),
    { class: 'form-control', required: true } %>
  </div>

  <div class="form-group col-xs-5">
    <%= f.label :balance, 'Saldo' %>
    <%= f.text_field :balance, type: "number", class: 'form-control', required: true %>
  </div>

  <div class="clearfix"></div>

  <hr width=92%>

  <div class="form-group col-xs-12">
    <%= f.label :detail, 'Detalle' %>
    <%= f.text_area :detail, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-xs-4">
    <%= f.label :created_at, 'Fecha' %>
    <%= f.date_field :created_at,
    value: @bank.created_at.nil? ? Date.today : @bank.created_at,
    class: 'form-control', required: true %>
  </div>

  <div class="form-group col-xs-3">
    <%# = f.label :trans_hour, 'Hora' %>
    <%# = f.text_field :trans_hour, class: 'form-control', required: true %>
    <%= f.label :created_at, 'Hora' %>
    <%= f.date_field :created_at,
    value: @bank.created_at.nil? ? Date.today : @bank.created_at.strftime('%H:%M'),
    class: 'form-control', required: true %>
  </div>

  <div class="form-group col-xs-4">
    <%= f.label :trans_value, 'Valor' %>
    <%= f.text_field :trans_value, type: "number", class: 'form-control', required: true %>
  </div>

  <div class="form-group col-xs-1">
    <%= f.label :verified, 'Vrf' %>
    <%= f.check_box :verified, class: 'form-control', required: true %>
  </div>

  <hr width=92%>
  <div class="clearfix"></div>

  <div class="actions text-center">
    <%= f.button :submit, class: "btn btn-success" do %>
      <i class='fa fa-plus'></i> Guardar
    <% end %>

    <%= link_to banks_path, class: "btn btn-warning" do %>
      <i class='fa fa-arrow-left'></i> Regresar
    <% end %>
  </div>

<% end %>

<div class="clearfix"></div>

app/views/banks/b_bancol.html.erb
<nav class="header-reg">
  <%= link_to 'Día', movements_path %> | <!-- Día, nuevo, consolidados -->

  <%= link_to 'Nuevo_', new_bank_path %>
  <%= link_to 'Ban-Col', '#' %>   <!-- Actividades programadas -->
  <%= link_to 'Conavi', '#' %> <!-- Eventos, Estadio, Macarena, TT, JPII... -->
  <%= link_to 'BIC', '#' %>  <!-- Agenda -->
  <%= link_to 'Credit', credit_path %>  <!-- Creditos, Financiaciones, .. -->
</nav>

<!-- _____________________________________________ -->

<div> <center>
  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Datos / Bancos / Bancolombia </span> <%= link_to 'Back', banks_path %>
    <span> Coltax OnLine </span> </h3>
  <h4> Bancolombia </h4> </center>
</div>

<table class="table table-hover table-striped datatable-plugin">
  <thead>
    <tr>
      <th>Nº</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Detalle</th>
      <th>Cuenta</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th>CB</th>
      <th>Banco</th>
      <th>Balance</th>
      <!-- <th>Users</th> -->
      <th>Vf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each_with_index do |bank, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= bank.created_at.strftime('%m/%d') %></td>
        <td><% unless bank.created_at.nil? %>
              <%= bank.created_at.strftime('%H:%M') %>
              <!--  + ' ' + bank.created_at_hour -->
            <% end %> </td>
        <td><%= bank.detail %></td>
        <td><%= bank.puc %></td>
        <td><%= bank.trans_type %></td>
        <td><%= bank.trans_value %></th>

        <td><%= bank.bank_id %></td>
        <td><%= bank.bank %></td>
        <td><%= bank.balance  %></th>
        <td><%= bank.verified %></td>

        <!-- <td><%= link_to 'Show', bank %></td> -->
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Delete', bank, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>

  </tbody>

</table>

  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span>  Bancos </span> <%= link_to 'Back', finanzas_path %> <span>/ Coltax </span> </h3>

<table width=100%>
  <tr>
      <td class="olive3">
          <nav class="header-reg">
            <ul><li> Bancol </li>
                <li> Ban_Colombia </li>
                <li> BIC </li>
                <li> Conavi </li>
                <li> BCH </li>
                <li> Colmena </li>
            </ul>
          </nav>
      </td>

      <td class="green2">
          <nav class="header-reg">
            <ul><li> Bogotá Md </li>
                <li> Bogotá Ap </li>
                <li> Ban_Agrario </li>
                <li> Cial_Antioqueño </li>
                <li> Davivienda </li>
                <li> Ganadero </li>
            </ul>
          </nav>
      </td>
    </tr>

    <tr>
      <td class="blue1" colspan=2>
          <nav class="header-reg">
            <ul><li> Citi Bank </li>
            </ul>
          </nav>
      </td>
  </tr>

  <tr>
      <td class="darkgreen" colspan=2>
          <nav class="header-reg green">
            <ul><li> Cooperativa de Ahorros de Antioquia </li>
            </ul>
          </nav>
      </td>
  </tr>
</table>


<br><h3.blue>Footer</h3><br><br>




<span><%= link_to 'Return Finances', finanzas_path %></span>

app/views/banks/b_bogota.html.erb
<nav class="header-reg">
  <%= link_to 'Nuevo_', new_bank_path %>
  <%= link_to 'Día', movements_path %> <!-- Día, nuevo, consolidados -->

  <%= link_to 'Bogotá1', '#' %> <!-- ... -->
  <%= link_to 'Bogotá2', '#' %> <!-- ... -->
  <%= link_to 'Credit', credit_path %>  <!-- ... -->
  <%= link_to 'Leasing', '#' %>  <!-- Agenda -->
</nav>


<div> <center>
  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Bancos / Bogotá </span> <%= link_to 'Back', banks_path %>
    <span>Coltax OnLine</span> </h3>
  <h4> Banco de Bogotá </h4> </center>

  <P>
  <nav>
    <ul>
        <li> Header </li>
        <li> Bogotá </li>
        <li> Bogotá_1 </li>
        <li> ----------------- </li>

    </ul>
  </nav>

</div>

app/views/banks/b_daviv.html.erb
<nav class="header-reg">
  <%= link_to 'Nuevo_', new_bank_path %>
  <%= link_to 'Día', movements_path %> <!-- Día, nuevo, consolidados -->

  <%= link_to 'Apart', '#' %> <!-- ... -->
  <%= link_to 'Casa', '#' %>  <!-- Agenda -->
  <%= link_to 'Credit', credit_path %>  <!-- Creditos, Financiaciones, .. -->
  <%= link_to 'Otros', '#' %> <!-- ... -->
</nav>


<div> <center>
  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Bancos / Davivienda </span> <%= link_to 'Back', banks_path %>
    <span>Coltax OnLine</span> </h3>

  <h4> Davivienda </h4>
  </center>

  <P>
  <nav>
    <ul>
        <li> Bancolombia </li>
        <li> nn </li>
        <li> nn </li>
        <li> ----------------- </li>

    </ul>
  </nav>

</div>

app/views/banks/edit.html.erb
<h4>Editing Bank</h4><br>

<%= render 'form', bank: @bank %>

<h2><center><P>
  <%= link_to 'Show', @bank %>  | 
  <%= link_to 'Back', banks_path %>
</center></h2>

app/views/banks/index.html.erb
<!-- Bancos -->
<nav class="header-reg">
  <%= link_to 'Nuevo!', new_bank_path %>

  <%= link_to 'BanCol', b_bancol_path %> <!-- Actividades programadas -->
  <%= link_to 'Bogotá', b_bogota_path %> <!-- ... -->
  <%= link_to 'Daviv ', b_daviv_path %>  <!-- Agenda -->
  <%= link_to 'Otros ', '#' %> <!-- Actividades programadas -->
</nav>

<div> <center>
  <h3 style="display: flex; justify-content: space-between; width: 100%;">
    <span> Datos / Bancos </span> <%= link_to 'Back', data_path %>
    <span> Coltax OnLine </span> </h3>
  <h4> Bancos y Corp_Ahorros </h4> </center>
</div>

<table class="table table-hover table-striped datatable-plugin">
  <thead>
    <tr>
      <th>Nº</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Detalle</th>
      <th>Cuenta</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th>CB</th>
      <th>Banco</th>
      <th>Balance</th>
      <!-- <th>Users</th> -->
      <th>Vf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each_with_index do |bank, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= bank.created_at.strftime('%m/%d') %></td>
        <td><% unless bank.created_at.nil? %>
              <%= bank.created_at.strftime('%H:%M') %>
            <% end %>
        <!--  + ' ' + bank.created_at_hour -->
        </td>
        <td><%= bank.detail %></td>
        <td><%= bank.puc %></td>
        <td><%= bank.trans_type %></td>
        <td><%= bank.trans_value %></td>

        <td><%= bank.bank_id %></td>
        <td><%= bank.bank %></td>
        <td><%= bank.balance + 1 %></td>
        <td><%= bank.verified %></td>

        <!-- <td><%= link_to 'Show', bank %></td> -->
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Delete', bank, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>


  <!-- Estados Bancarios -->
  <hr class="separator">
  <h6 style="display: flex; justify-content: space-between; width: 100%;">
    <span> ♦ Datos </span> <%= link_to '◄', data_path %>
    <%= link_to '►', banks_path %> <span> Bancos <%= Time.now.strftime("%Y")%> ♦ </span> </h6>
  <hr class="separator">

  <div class="row">
    <div class="col-xs-2 blue0"><h6>Bancos</h6></div>
    <div class="col-xs-2 blue0"><h6>Dia</h6></div>
    <div class="col-xs-2 blue0"><h6>Sem</h6></div>
    <div class="col-xs-2 blue0"><h6>Mes</h6></div>
    <div class="col-xs-3 blue0"><h6>Total</h6></div>
    <div class="col-xs-1 blue0"><h6> ♣ </h6></div>
  </div>

  <div class="row">
    <div class="col-xs-2 yellow"><h6 class="black">Bank<span class="blue_f">¹</span>_dp</h6></div>
    <div class="col-xs-2 fuchs4"><h6><%= to_currency(@ad_bd) %></h6></div>
    <div class="col-xs-2 glima4"><h6><%= to_currency(@aw_bd) %></h6></div>
    <div class="col-xs-2 marin4"><h6><%= to_currency(@am_bd) %></h6></div>
    <div class="col-xs-3 marin2"><h6><%= to_currency(@ay_bd) %></h6></div>
    <div class="col-xs-1 blue  "><h5><%= to_currency(@nn_n ) %></h5></div>
  </div>
  <div class="row">
    <div class="col-xs-2 yellow"><h6 class="black">Bank<span class="blue_f">²</span>_rt</h6></div>
    <div class="col-xs-2 fuchs2"><h6><%= to_currency(@ad_br) %></h6></div>
    <div class="col-xs-2 glima2"><h6><%= to_currency(@aw_br) %></h6></div>
    <div class="col-xs-2 marin2"><h6><%= to_currency(@am_br) %></h6></div>
    <div class="col-xs-3 marin1"><h6><%= to_currency(@ay_br) %></h6></div>
    <div class="col-xs-1 blue1 "><h5><%= to_currency(@nn_n ) %></h5></div>
  </div>
  <div class="row">
    <div class="col-xs-2 yellow"><h6 class="black">Bank<span class="blue_f">³</span>_pg</h6></div>
    <div class="col-xs-2 fuchs1"><h6><%= to_currency(@ad_bc) %></h6></div>
    <div class="col-xs-2 marin2"><h6><%= to_currency(@aw_bc) %></h6></div>
    <div class="col-xs-2 marin1"><h6><%= to_currency(@am_bc) %></h6></div>
    <div class="col-xs-3 marin0"><h6><%= to_currency(@ay_bc) %></h6></div>
    <div class="col-xs-1 blue  "><h5><%= to_currency(@nn_n ) %></h5></div>
  </div>
  <div class="row">
    <div class="col-xs-2 yellow"><h6 class="black">Bank<span class="blue_f">°</span>_cb</h6></div>
    <div class="col-xs-2 fuchsi"><h6><%= to_currency(@ad_bo) %></h6></div>
    <div class="col-xs-2 marin1"><h6><%= to_currency(@aw_bo) %></h6></div>
    <div class="col-xs-2 marin0"><h6><%= to_currency(@am_bo) %></h6></div>
    <div class="col-xs-3 marina"><h6><%= to_currency(@ay_bo) %></h6></div>
    <div class="col-xs-1 blue1 "><h6><%= to_currency(@nn_n ) %></h6></div>
  </div>

  <div class="row" border=1>
    <div class="col-xs-2 blue0"><h6 class="white text-center">Neto</h6></div>
    <div class="col-xs-2 blue0"><h6><%= to_currency(@ad_nb) %></h6></div>
    <div class="col-xs-2 blue0"><h6><%= to_currency(@aw_nb) %></h6></div>
    <div class="col-xs-2 blue0"><h6><%= to_currency(@am_nb) %></h6></div>
    <div class="col-xs-3 blue0"><h6><%= to_currency(@ay_nb) %></h6></div>
    <div class="col-xs-1 blue0"><h6><%= to_currency(@nn_n ) %></h6></div>
  </div>

  <hr class="separator">


  <h3 style="display: flex; justify-content: space-between; width: 100%;">
      <span>  Bancos </span> <%= link_to 'Back', finanzas_path %> <span>/ Coltax </span> </h3>

  <table width=100%>
    <tr><td class="olive3">
            <nav class="header-reg">
              <ul><li> Bancolombia </li>
                  <li> Citi Bank </li>
                  <li> Davivienda </li>
              </ul>
            </nav>
        </td>

        <td class="green2">
            <nav class="header-reg">
              <ul><li> Banco Agrario </li>
                  <li> Bogotá Ap </li>
                  <li> Bogotá Md </li>
              </ul>
            </nav>
        </td>
    </tr>

    <tr><td class="blue1" colspan=1>
            <nav class="header-reg">
              <ul><li> Banco de Colombia </li>
                <li> BIC </li>
                <li> Conavi </li>
                <li> BCSH_Colmena </li>
              </ul>
            </nav>
        </td>

        <td class="green2">
            <nav class="header-reg">
              <ul><li> Ban_Agrario </li>
                  <li> BCH </li>
                  <li> Cial_Antioqueño </li>
                  <li> Ganadero </li>
              </ul>
            </nav>
        </td>

    </tr>

    <tr>
        <td class="darkgreen" colspan=2>
            <nav class="header-reg green">
              <ul><li> Cooperativa de Ahorros de Antioquia </li>
              </ul>
            </nav>
        </td>
    </tr>
  </table>

<hr class="separator">
<h3 class="white">Footer</h3>
<h4 class="navy"><span><%= link_to 'Return Finances', finanzas_path %></span></h4>
<hr class="separator">

app/views/banks/new.html.erb
<div class="container-coltax">
  <h4>Bancos, Nuevo registro</h4>
  <%= render 'form', bank: @bank %>
</div>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Puc:</strong>
  <%= @bank.puc %>
</p>

<p>
  <strong>Trans type:</strong>
  <%= @bank.trans_type %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @bank.detail %>
</p>

<p>
  <strong>Trans value:</strong>
  <%= @bank.trans_value %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @bank.balance %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @bank.bank_id %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @bank.bank %>
</p>

<p>
  <strong>Users:</strong>
  <%= @bank.users %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @bank.verified %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>