config/routes.rb
Rails.application.routes.draw do
  resources :pucs
  resources :banks
  resources :movements

  root to: redirect('home')
  devise_for :users, controllers: {
    :registrations => "users/registrations"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'movements#home', as: 'home'
  get '/show', to: 'movements#show', as: 'show'
  get '/cupon', to: 'movements#_cupones_header', as: '_cupones_header'
  get '/webmaster', to: 'application#_superadmin_header', as: '_superadmin_header'

  get '/todos', to: 'movements#see_all', as: 'see_all'
  get '/weeks', to: 'movements#see_weeks', as: 'see_weeks'
  get '/months', to: 'movements#see_months', as: 'see_months'
  get '/tiempo', to: 'movements#see_tiempo', as: 'see_tiempo'

  get '/redes', to: 'movements#redes', as: 'redes'
  get '/chat', to: 'movements#rs_chat', as: 'rs_chat'
  get '/agenda', to: 'movements#rs_agenda', as: 'rs_agenda'
  get '/eventos', to: 'movements#rs_eventos', as: 'rs_eventos'
  get '/notas', to: 'movements#rs_notas', as: 'rs_notas'

  get '/datos', to: 'movements#data', as: 'data'
  get '/bancos', to: 'banks#index', as: 'bancos'
  get '/bancol', to: 'banks#b_bancol', as: 'b_bancol'
  get '/bogota', to: 'banks#b_bogota', as: 'b_bogota'
  get '/daviv',  to: 'banks#b_daviv', as: 'b_daviv'

  get '/contab', to: 'movements#contab', as: 'contab'
  get '/finanzas', to: 'movements#finanzas', as: 'finanzas'
  get '/credit', to: 'movements#credit', as: 'credit'

  get '/movmed', to: 'movements#movmed', as: 'movmed'
  get '/leyes', to: 'movements#n_leyes', as: 'n_leyes'
  get '/normas', to: 'movements#normas', as: 'normas'
  get '/pp', to: 'movements#movm_pp', as: 'movm_pp'
  get '/runt', to: 'movements#n_runt', as: 'n_runt'

  get '/flota', to: 'movements#tr_flota', as: 'tr_flota'
  get '/andaluz', to: 'movements#vx_andaluz', as: 'vx_andaluz'
  get '/athos', to: 'movements#vx_athos', as: 'vx_athos'
  get '/athos_bitac', to: 'movements#vx_athos_bitac', as: 'vx_athos_bitac'
  get '/athos_matric', to: 'movements#vx_athos_matric', as: 'vx_athos_matric'
  get '/taxis', to: 'movements#vx_taxis', as: 'vx_taxis'

  get '/coltrans', to: 'movements#tr_coltrans', as: 'tr_coltrans'
  get '/dimax', to: 'movements#vc_dimax_', as: 'vc_dimax_'
  get '/dimax_agree', to: 'movements#vc_dmx_contratos', as: 'vc_dmx_contratos'
  get '/dimax_bitac', to: 'movements#vc_dimax_bitac', as: 'vc_dimax_bitac'
  get '/dimax_matric', to: 'movements#vc_dimax_matric', as: 'vc_dimax_matric'

  get '/autos', to: 'movements#vc_autos', as: 'vc_autos'
  get '/golf', to: 'movements#vc_golf_', as: 'vc_golf_'
  get '/piaggio', to: 'movements#vm_piaggio', as: 'vm_piaggio'

  get '/taller', to: 'movements#tr_taller', as: 'tr_taller'
  get '/mec_aut', to: 'movements#tr_tutors', as: 'tr_tutors'

  as :user do
    get 'admin', to: 'devise/sessions#new'
    get 'reset_password', to: 'devise/passwords#new'
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info
  before_action :authenticate_user!, only: [:home_admin]

  def home
  end

  def home_admin
    @traffic = Visit.joins(:campaign)
                    .where('campaigns.active = true and visits.campaign_id = campaigns.id').order(:register_date)
    @generated_coupons = Coupon.joins(:campaign).select("coupons.created_at")
                               .where('campaigns.id = coupons.campaign_id and campaigns.active = true').order(:created_at)
    @invalid_coupons = Coupon.where(bounced: true).count
    if current_user.super?
      @redeemed_coupons = Coupon.joins(:campaign)
                                .where('campaigns.id = coupons.campaign_id and campaigns.active = true and coupons.redeemed = true').order(:created_at)
      @bill_value = Coupon.joins(:campaign)
                          .where('campaigns.id = coupons.campaign_id and campaigns.active = true and coupons.redeemed = true').order(:created_at)
    else
      @redeemed_coupons = Coupon.joins(:campaign)
                                .where('campaigns.id = coupons.campaign_id and campaigns.active = true and coupons.redeemed = true and coupons.shop_id = :shop_id',
                                        { shop_id: current_user.shop_id }).order(:created_at)
      @bill_value = Coupon.joins(:campaign)
                          .where('campaigns.id = coupons.campaign_id and campaigns.active = true and coupons.redeemed = true and coupons.shop_id = :shop_id',
                                  { shop_id: current_user.shop_id }).order(:created_at)
    end
  end

  def shops_info
    @campaign = Campaign.where(slug: params[:slug]).first
    @shops = Shop.all
    @cities = City.all.order(:name)
  end

  def thank_you
    @campaign = Campaign.find_by(active: true)
  end

  private
    def save_visit
      visit = Visit.find_by(register_date: Date.current, campaign_id: @campaign.id)
      if visit.nil?
        Visit.create(campaign_id: @campaign.id, register_date: Date.current, counter: 1)
      else
        visit.counter += 1
        visit.save
      end
    end

  protected
    def after_sign_in_path_for(resource)
      movements_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_coupon_form.html.erb
<%= form_for(:coupon,  url: obtain_coupon_path, id: "obtain-coupon") do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: "*Nombre completo", class: "form-control", required: true%>
  </div>
  <div class="form-group">
    <%= f.text_field :identification, placeholder: "*Identificación", class: "form-control", required: true%>
  </div>
  <div class="form-group">
    <%= f.text_field :email, placeholder: "*Correo electrónico", class: "form-control", required: true, type: "email"%>
  </div>
  <div class="form-group">
    <%= f.text_field :phone, placeholder: "*Celular", class: "form-control", required: true, type: "number"%>
  </div>
  <div class="form-group">
    <%= f.text_field :birthday, placeholder: "*Cumpleaños", class: "form-control", required: true, type: "date" %>
  </div>
  <div class="form-group">
    <%= f.select :city_name, @campaign.cities.collect { |c| [c] },
                                         { prompt: "Elige tu ciudad"},
                                         { class: 'form-control shadow'}  %>
    <%= f.hidden_field :campaign_id, value: @campaign.id if !@campaign.nil? %>
  </div>
  <div>
    <p> * Haciendo click en GENERA TU BONO estás aceptando nuestros
      <%= content_tag :a, "términos y condiciones", href: "#terms_and_coditions", data: {toggle: 'modal'}%>
       y aceptas recibir información vía correo electrónico de Estudio de Moda S.A.</p>
  </div>
  <div class="actions">
     <%= f.submit "Genera tu bono", class: "btn btn-send", style: "background-color: #{@campaign.color_buttons if !@campaign.nil? }; color: #FFF" %>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     toastr.options = {
      "closeButton": false,
      "debug": false,
      "newestOnTop": false,
      "progressBar": true,
      "positionClass": "toast-top-right",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "1000",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }

     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>

     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/application/_superadmin_header.html.erb
<%= nav_bar brand: "Coltªx", brand_link: movements_path, responsive: true do %>

  <% menu_group pull: :right do %>
    <%= menu_item " • Home", home_path %>
    <%= menu_item " • Users", new_user_registration_path %>

    <%= menu_item " ► Cerrar Sesión →", destroy_user_session_path, :method => :delete %>
  <% end %>
<% end %>

app/views/application/home.html.erb
<div style = "background-color: green; align: left;">
  <%= image_tag 'public/favicon.png', id:''%>
</div>

<%= nav_bar brand: "Coltax°", brand_link: root_path, responsive: true do %>
  <% menu_group pull: :right do %>
    <%= menu_item " • Quienes somos", '#' %>
    <%= menu_item " • Contactos", '#'  %>
    <%= menu_item " • Foros", "https://foro.online/" %>
    <%= menu_item " • Servicios", '#' %>
    <%= menu_item " ? ", '#'  %>
    <!-- <%= menu_item ' Iniciar sesión', admin_path %> -->
  <% end %>
<% end %>

  <center>
  <div style = "background-color: black;">
    <br><%= image_tag 'horse.jpg', id:'horse'%><br>
  </div> <br>

  <div style = "background-color: blue" width="50%">
    <!--  Views/aplic/home -->
    <h4 class="yellow"><%= link_to 'Iniciar sesión', admin_path %> </H4>
  </div>
  </center>